version: '3.8'

services:
  ev-charge-calculator:
    container_name: ev-charge-calculator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
